# Usar una imagen base de Nginx
FROM nginx:alpine

# Copiar la configuración de Nginx
COPY nginx.conf /etc/nginx/nginx.conf

# Copiar el archivo index.html que creamos para el inicio
COPY index.html /usr/share/nginx/html/index.html

# Exponer el puerto en el que se ejecutará Nginx
EXPOSE 8080
